# Generated by Django 3.1.3 on 2020-11-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_auto_20201120_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='name',
            field=models.CharField(choices=[('Mt 1', 'Mid-term 1'), ('Mt 2', 'Mid-term 2'), ('Mv 1', 'Mid-term viva 1'), ('Mv 1', 'Mid-term viva 1'), ('FPE', ' Final practical'), ('TA', 'Teacher Asessment'), ('Semester End Exam', 'Semester End Exam')], default='Internal test 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='marksclass',
            name='name',
            field=models.CharField(choices=[('Mt 1', 'Mid-term 1'), ('Mt 2', 'Mid-term 2'), ('Mv 1', 'Mid-term viva 1'), ('Mv 1', 'Mid-term viva 1'), ('FPE', ' Final practical'), ('TA', 'Teacher Asessment'), ('Semester End Exam', 'Semester End Exam')], default='Internal test 1', max_length=50),
        ),
    ]
