# Generated by Django 3.1.3 on 2020-11-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_auto_20201121_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Room',
        ),
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
