# Generated by Django 3.1.3 on 2020-11-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_auto_20201121_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='meeting_link',
            field=models.URLField(blank=True),
        ),
    ]
