# Generated by Django 3.1.3 on 2020-11-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0025_auto_20201121_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Rollno',
            field=models.CharField(max_length=50, primary_key='True', serialize=False),
        ),
    ]
