# Generated by Django 2.2.17 on 2020-11-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0027_auto_20201121_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
