# Generated by Django 2.2.17 on 2020-11-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0029_auto_20201121_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, choices=[('Exam', 'Exam'), ('Result', 'Result'), ('Holiday', 'Holiday'), ('General', 'General')], max_length=30)),
                ('Heading', models.CharField(max_length=200)),
                ('Date', models.DateField(blank=True)),
            ],
        ),
    ]
