# Generated by Django 2.2.17 on 2020-11-22 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0031_alert_file_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='Date',
            field=models.DateField(blank=True, default=datetime.date(2020, 11, 22)),
        ),
    ]
