# Generated by Django 2.2.17 on 2020-11-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0033_auto_20201122_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name_plural': 'Alerts'},
        ),
    ]
