# Generated by Django 3.1.3 on 2020-11-23 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0034_auto_20201122_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='Date',
            field=models.DateField(blank=True, default=datetime.date(2020, 11, 23)),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
