# Generated by Django 2.2.17 on 2020-11-23 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0034_auto_20201122_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='Date',
            field=models.DateField(blank=True, default=datetime.date(2020, 11, 23)),
        ),
    ]
